resolver: lts-2.10
flags: {}
packages:
- '.'
extra-deps:
  # lexer-applicative and tuples-homogenous are not in LTS 2.10;
  # will be in the next one
  - lexer-applicative-2.1
  - tuples-homogenous-h98-0.1.1.0

  # LTS 2.10 contains an old (0.4.x) version of srcloc, so we override it
  - srcloc-0.5.0.2
  # Depends on srcloc, thus can't be taken from LTS. Specify manually.
  - mainland-pretty-0.4.0.0
